/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Core Printing
 #	author : miyako
 #	11/09/10
 #
 # --------------------------------------------------------------------------------*/



// --- Page Format
void CP_Get_orientation(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_ORIENTATION(sLONG_PTR *pResult, PackagePtr pParams);
void CP_Get_scale(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_SCALE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Print Settings
void CP_Get_copies(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_COPIES(sLONG_PTR *pResult, PackagePtr pParams);
void CP_Get_first_page(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_FIRST_PAGE(sLONG_PTR *pResult, PackagePtr pParams);
void CP_get_last_page(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_LAST_PAGE(sLONG_PTR *pResult, PackagePtr pParams);
void CP_get_job_name(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_JOB_NAME(sLONG_PTR *pResult, PackagePtr pParams);
void CP_get_duplex(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_DUPLEX(sLONG_PTR *pResult, PackagePtr pParams);
void CP_get_collate(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_COLLATE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Printer
void CP_GET_PRINTER_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void CP_get_default_printer(sLONG_PTR *pResult, PackagePtr pParams);
void CP_SET_DEFAULT_PRINTER(sLONG_PTR *pResult, PackagePtr pParams);
void CP_get_printer_state(sLONG_PTR *pResult, PackagePtr pParams);

// --- XML
void CP_XML_Get_page_format(sLONG_PTR *pResult, PackagePtr pParams);
void CP_XML_Get_print_settings(sLONG_PTR *pResult, PackagePtr pParams);
void CP_XML_SET_PAGE_FORMAT(sLONG_PTR *pResult, PackagePtr pParams);
void CP_XML_SET_PRINT_SETTINGS(sLONG_PTR *pResult, PackagePtr pParams);
